package mmal

import (
	"testing"
	"unsafe"
)

func TestParametersCameraStructSizes(t *testing.T) {
	testStructSizes(t, []sizeTest{
		{Go: unsafe.Sizeof(_parameterThumbnailConfig{}), C: unsafe.Sizeof(_MMAL_PARAMETER_THUMBNAIL_CONFIG{})},
		{Go: unsafe.Sizeof(_parameterEXIF{}), C: unsafe.Sizeof(_MMAL_PARAMETER_EXIF{})},
		{Go: unsafe.Sizeof(_parameterExposureMode{}), C: unsafe.Sizeof(_MMAL_PARAMETER_EXPOSUREMODE{})},
		{Go: unsafe.Sizeof(_parameterExposureMeteringMode{}), C: unsafe.Sizeof(_MMAL_PARAMETER_EXPOSUREMETERINGMODE{})},
		{Go: unsafe.Sizeof(_parameterAWBMode{}), C: unsafe.Sizeof(_MMAL_PARAMETER_AWBMODE{})},
		{Go: unsafe.Sizeof(_parameterImageFX{}), C: unsafe.Sizeof(_MMAL_PARAMETER_IMAGEFX{})},
		{Go: unsafe.Sizeof(_parameterImageFXParameters{}), C: unsafe.Sizeof(_MMAL_PARAMETER_IMAGEFX_PARAMETERS{})},
		{Go: unsafe.Sizeof(_parameterColourFX{}), C: unsafe.Sizeof(_MMAL_PARAMETER_COLOURFX{})},
		{Go: unsafe.Sizeof(_parameterCameraSTCMode{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_STC_MODE{})},
		{Go: unsafe.Sizeof(_parameterFlickerAvoid{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FLICKERAVOID{})},
		{Go: unsafe.Sizeof(_parameterFlash{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FLASH{})},
		{Go: unsafe.Sizeof(_parameterRedeye{}), C: unsafe.Sizeof(_MMAL_PARAMETER_REDEYE{})},
		{Go: unsafe.Sizeof(_parameterFocus{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FOCUS{})},
		{Go: unsafe.Sizeof(_parameterCaptureStatus{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAPTURE_STATUS{})},
		{Go: unsafe.Sizeof(_parameterFocusStatus{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FOCUS_STATUS{})},
		{Go: unsafe.Sizeof(_parameterFaceTrack{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FACE_TRACK{})},
		{Go: unsafe.Sizeof(ParameterFaceTrackFace{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FACE_TRACK_FACE{})},
		{Go: unsafe.Sizeof(_parameterFaceTrackResults{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FACE_TRACK_RESULTS{})},
		{Go: unsafe.Sizeof(_parameterCameraConfig{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_CONFIG{})},
		{Go: unsafe.Sizeof(ParameterCameraInfoCamera{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_INFO_CAMERA{})},
		{Go: unsafe.Sizeof(ParameterCameraInfoFlash{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_INFO_FLASH{})},
		{Go: unsafe.Sizeof(_parameterCameraInfo{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_INFO{})},
		{Go: unsafe.Sizeof(_parameterCaptureMode{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAPTUREMODE{})},
		{Go: unsafe.Sizeof(ParameterFocusRegion{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FOCUS_REGION{})},
		{Go: unsafe.Sizeof(_parameterFocusRegions{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FOCUS_REGIONS{})},
		{Go: unsafe.Sizeof(_parameterInputCrop{}), C: unsafe.Sizeof(_MMAL_PARAMETER_INPUT_CROP{})},
		{Go: unsafe.Sizeof(_parameterSensorInformation{}), C: unsafe.Sizeof(_MMAL_PARAMETER_SENSOR_INFORMATION{})},
		{Go: unsafe.Sizeof(_parameterFlashSelect{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FLASH_SELECT{})},
		{Go: unsafe.Sizeof(_parameterFieldOfView{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FIELD_OF_VIEW{})},
		{Go: unsafe.Sizeof(_parameterDRC{}), C: unsafe.Sizeof(_MMAL_PARAMETER_DRC{})},
		{Go: unsafe.Sizeof(_parameterAlgorithmControl{}), C: unsafe.Sizeof(_MMAL_PARAMETER_ALGORITHM_CONTROL{})},
		{Go: unsafe.Sizeof(_parameterCameraUseCase{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_USE_CASE{})},
		{Go: unsafe.Sizeof(_parameterFPSRange{}), C: unsafe.Sizeof(_MMAL_PARAMETER_FPS_RANGE{})},
		{Go: unsafe.Sizeof(_parameterZeroshutterlag{}), C: unsafe.Sizeof(_MMAL_PARAMETER_ZEROSHUTTERLAG{})},
		{Go: unsafe.Sizeof(_parameterAWBGains{}), C: unsafe.Sizeof(_MMAL_PARAMETER_AWB_GAINS{})},
		{Go: unsafe.Sizeof(_parameterCameraSettings{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_SETTINGS{})},
		{Go: unsafe.Sizeof(_parameterPrivacyIndicator{}), C: unsafe.Sizeof(_MMAL_PARAMETER_PRIVACY_INDICATOR{})},
		{Go: unsafe.Sizeof(_parameterCameraAnnotate{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_ANNOTATE{})},
		{Go: unsafe.Sizeof(_parameterCameraAnnotateV2{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_ANNOTATE_V2{})},
		{Go: unsafe.Sizeof(_parameterCameraAnnotateV3{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_ANNOTATE_V3{})},
		{Go: unsafe.Sizeof(_parameterStereoscopicMode{}), C: unsafe.Sizeof(_MMAL_PARAMETER_STEREOSCOPIC_MODE{})},
		{Go: unsafe.Sizeof(_parameterCameraInterface{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_INTERFACE{})},
		{Go: unsafe.Sizeof(_parameterCameraClockingMode{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_CLOCKING_MODE{})},
		{Go: unsafe.Sizeof(_parameterCameraRxConfig{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_RX_CONFIG{})},
		{Go: unsafe.Sizeof(_parameterCameraRxTiming{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CAMERA_RX_TIMING{})},
		{Go: unsafe.Sizeof(_parameterLensShading{}), C: unsafe.Sizeof(_MMAL_PARAMETER_LENS_SHADING{})},
		{Go: unsafe.Sizeof(_parameterResize{}), C: unsafe.Sizeof(_MMAL_PARAMETER_RESIZE{})},
		{Go: unsafe.Sizeof(_parameterCrop{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CROP{})},
		{Go: unsafe.Sizeof(ParameterCCM{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CCM{})},
		{Go: unsafe.Sizeof(_parameterCustomCCM{}), C: unsafe.Sizeof(_MMAL_PARAMETER_CUSTOM_CCM{})},

		{Go: unsafe.Alignof(_parameterThumbnailConfig{}), C: unsafe.Alignof(_MMAL_PARAMETER_THUMBNAIL_CONFIG{})},
		{Go: unsafe.Alignof(_parameterEXIF{}), C: unsafe.Alignof(_MMAL_PARAMETER_EXIF{})},
		{Go: unsafe.Alignof(_parameterExposureMode{}), C: unsafe.Alignof(_MMAL_PARAMETER_EXPOSUREMODE{})},
		{Go: unsafe.Alignof(_parameterExposureMeteringMode{}), C: unsafe.Alignof(_MMAL_PARAMETER_EXPOSUREMETERINGMODE{})},
		{Go: unsafe.Alignof(_parameterAWBMode{}), C: unsafe.Alignof(_MMAL_PARAMETER_AWBMODE{})},
		{Go: unsafe.Alignof(_parameterImageFX{}), C: unsafe.Alignof(_MMAL_PARAMETER_IMAGEFX{})},
		{Go: unsafe.Alignof(_parameterImageFXParameters{}), C: unsafe.Alignof(_MMAL_PARAMETER_IMAGEFX_PARAMETERS{})},
		{Go: unsafe.Alignof(_parameterColourFX{}), C: unsafe.Alignof(_MMAL_PARAMETER_COLOURFX{})},
		{Go: unsafe.Alignof(_parameterCameraSTCMode{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_STC_MODE{})},
		{Go: unsafe.Alignof(_parameterFlickerAvoid{}), C: unsafe.Alignof(_MMAL_PARAMETER_FLICKERAVOID{})},
		{Go: unsafe.Alignof(_parameterFlash{}), C: unsafe.Alignof(_MMAL_PARAMETER_FLASH{})},
		{Go: unsafe.Alignof(_parameterRedeye{}), C: unsafe.Alignof(_MMAL_PARAMETER_REDEYE{})},
		{Go: unsafe.Alignof(_parameterFocus{}), C: unsafe.Alignof(_MMAL_PARAMETER_FOCUS{})},
		{Go: unsafe.Alignof(_parameterCaptureStatus{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAPTURE_STATUS{})},
		{Go: unsafe.Alignof(_parameterFocusStatus{}), C: unsafe.Alignof(_MMAL_PARAMETER_FOCUS_STATUS{})},
		{Go: unsafe.Alignof(_parameterFaceTrack{}), C: unsafe.Alignof(_MMAL_PARAMETER_FACE_TRACK{})},
		{Go: unsafe.Alignof(ParameterFaceTrackFace{}), C: unsafe.Alignof(_MMAL_PARAMETER_FACE_TRACK_FACE{})},
		{Go: unsafe.Alignof(_parameterFaceTrackResults{}), C: unsafe.Alignof(_MMAL_PARAMETER_FACE_TRACK_RESULTS{})},
		{Go: unsafe.Alignof(_parameterCameraConfig{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_CONFIG{})},
		{Go: unsafe.Alignof(ParameterCameraInfoCamera{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_INFO_CAMERA{})},
		{Go: unsafe.Alignof(ParameterCameraInfoFlash{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_INFO_FLASH{})},
		{Go: unsafe.Alignof(_parameterCameraInfo{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_INFO{})},
		{Go: unsafe.Alignof(_parameterCaptureMode{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAPTUREMODE{})},
		{Go: unsafe.Alignof(ParameterFocusRegion{}), C: unsafe.Alignof(_MMAL_PARAMETER_FOCUS_REGION{})},
		{Go: unsafe.Alignof(_parameterFocusRegions{}), C: unsafe.Alignof(_MMAL_PARAMETER_FOCUS_REGIONS{})},
		{Go: unsafe.Alignof(_parameterInputCrop{}), C: unsafe.Alignof(_MMAL_PARAMETER_INPUT_CROP{})},
		{Go: unsafe.Alignof(_parameterSensorInformation{}), C: unsafe.Alignof(_MMAL_PARAMETER_SENSOR_INFORMATION{})},
		{Go: unsafe.Alignof(_parameterFlashSelect{}), C: unsafe.Alignof(_MMAL_PARAMETER_FLASH_SELECT{})},
		{Go: unsafe.Alignof(_parameterFieldOfView{}), C: unsafe.Alignof(_MMAL_PARAMETER_FIELD_OF_VIEW{})},
		{Go: unsafe.Alignof(_parameterDRC{}), C: unsafe.Alignof(_MMAL_PARAMETER_DRC{})},
		{Go: unsafe.Alignof(_parameterAlgorithmControl{}), C: unsafe.Alignof(_MMAL_PARAMETER_ALGORITHM_CONTROL{})},
		{Go: unsafe.Alignof(_parameterCameraUseCase{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_USE_CASE{})},
		{Go: unsafe.Alignof(_parameterFPSRange{}), C: unsafe.Alignof(_MMAL_PARAMETER_FPS_RANGE{})},
		{Go: unsafe.Alignof(_parameterZeroshutterlag{}), C: unsafe.Alignof(_MMAL_PARAMETER_ZEROSHUTTERLAG{})},
		{Go: unsafe.Alignof(_parameterAWBGains{}), C: unsafe.Alignof(_MMAL_PARAMETER_AWB_GAINS{})},
		{Go: unsafe.Alignof(_parameterCameraSettings{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_SETTINGS{})},
		{Go: unsafe.Alignof(_parameterPrivacyIndicator{}), C: unsafe.Alignof(_MMAL_PARAMETER_PRIVACY_INDICATOR{})},
		{Go: unsafe.Alignof(_parameterCameraAnnotate{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_ANNOTATE{})},
		{Go: unsafe.Alignof(_parameterCameraAnnotateV2{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_ANNOTATE_V2{})},
		{Go: unsafe.Alignof(_parameterCameraAnnotateV3{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_ANNOTATE_V3{})},
		{Go: unsafe.Alignof(_parameterStereoscopicMode{}), C: unsafe.Alignof(_MMAL_PARAMETER_STEREOSCOPIC_MODE{})},
		{Go: unsafe.Alignof(_parameterCameraInterface{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_INTERFACE{})},
		{Go: unsafe.Alignof(_parameterCameraClockingMode{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_CLOCKING_MODE{})},
		{Go: unsafe.Alignof(_parameterCameraRxConfig{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_RX_CONFIG{})},
		{Go: unsafe.Alignof(_parameterCameraRxTiming{}), C: unsafe.Alignof(_MMAL_PARAMETER_CAMERA_RX_TIMING{})},
		{Go: unsafe.Alignof(_parameterLensShading{}), C: unsafe.Alignof(_MMAL_PARAMETER_LENS_SHADING{})},
		{Go: unsafe.Alignof(_parameterResize{}), C: unsafe.Alignof(_MMAL_PARAMETER_RESIZE{})},
		{Go: unsafe.Alignof(_parameterCrop{}), C: unsafe.Alignof(_MMAL_PARAMETER_CROP{})},
		{Go: unsafe.Alignof(ParameterCCM{}), C: unsafe.Alignof(_MMAL_PARAMETER_CCM{})},
		{Go: unsafe.Alignof(_parameterCustomCCM{}), C: unsafe.Alignof(_MMAL_PARAMETER_CUSTOM_CCM{})},
	})
}
